import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { AppFooter, AppHeader } from "@/components/container";
import Provider from "@/components/provider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const theme = cookies().get("theme")?.value as "light"|"dark" || "system";

    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider
                    theme={theme}
                >                    
                    <AppHeader />
                    {children}
                    <AppFooter />
                </Provider>
            </body>
        </html>
    );
}
